import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="en">
      <body className="dark">
        <div className="flex flex-col min-h-screen dark:bg-gray-800">
          <header className="bg-gray-900 dark:bg-gray-800 text-white py-4 px-4">
            <nav className="flex items-center">
              <div>
                <Link className="text-white border-b-2 border-transparent hover:text-gray-300 hover:border-gray-300" href="/about">
                  About Page
                </Link>
              </div>
            </nav>
          </header>

          <main className="flex-1 flex container items-center justify-center mx-auto p-4">{children}</main>

          <footer className="bg-gray-900 dark:bg-gray-800 text-white py-4 px-4">
            <p className="text-center">&copy; {new Date().getFullYear()} KepaMax Inc.</p>
          </footer>
        </div>
      </body>

    </html>
  );
}
